# Generated by Django 5.0.6 on 2024-06-16 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='adresss',
            new_name='adress',
        ),
    ]
