# Generated by Django 5.0.6 on 2024-06-16 23:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_adresss_records_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
